enabled: true

# Namespace for the WireGuard deployment
namespace: wireguard

# ArgoCD configuration
argocd:
  project: default
  destinationName: in-cluster
  repoURL: https://k8s-at-home.com/charts/
  targetRevision: 1.4.2

# Image configuration
image:
  repository: linuxserver/wireguard
  tag: latest
  pullPolicy: IfNotPresent

# Timezone configuration
timezone: UTC

# Controller configuration
controller:
  replicas: 1

# Environment variables
env:
  PUID: "0"
  PGID: "0"
  TZ: UTC
  SERVERURL: "auto"
  PEERDNS: "auto"
  INTERNAL_SUBNET: "10.13.13.0/24"
  ALLOWEDIPS: "0.0.0.0/0"
  PEERS: "3"
  LOG_CONFS: "true"

# Persistence configuration
persistence:
  size: 1Gi
  nodeAffinity: raspberrypi
  config:
    enabled: true

# Ingress configuration
ingress:
  enabled: true
  class: traefik
  host: wireguard.dmascotte.com
  tls: true
  tlsSecretName: cert-manager-dmascotte-certificate

# Resource constraints
resources:
  requests:
    memory: 128Mi
    cpu: 100m
  limits:
    memory: 512Mi

# Network configuration - matches k8s-at-home chart format
service:
  main:
    enabled: true
    type: LoadBalancer
    loadBalancerIP: 192.168.1.2
    externalTrafficPolicy: Local
    annotations:
      metallb.universe.tf/address-pool: metallb-ip-pool
      metallb.universe.tf/allow-shared-ip: "metallb-ip-pool"
    ports:
      http:
        enabled: false
      vpn:
        enabled: true
        port: 51820
        protocol: UDP
        targetPort: 51820
        nodePort: 31820

# Security context
securityContext:
  privileged: true # Needed for network access
  capabilities:
    add:
      - NET_ADMIN
      - SYS_MODULE
      - SYS_ADMIN

# Pod security context
podSecurityContext:
  runAsUser: 0
  runAsGroup: 0
  fsGroup: 0