{{- if .Values.enabled }}
---
# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace | default "adguard" }}
---
# Persistent Volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-data-adguard-home
  namespace: {{ .Values.namespace | default "adguard" }}
spec:
  storageClassName: local-path
  capacity:
    storage: {{ .Values.persistence.size | default "1Gi" }}
  accessModes:
    - ReadWriteMany
  local:
    fsType: ""
    path: /mnt/ssd/app-data/adguard-home
  persistentVolumeReclaimPolicy: Retain
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
            - {{ .Values.persistence.nodeAffinity | default "raspberrypi" }}
---
# Persistent Volume Claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-adguard-home
  namespace: {{ .Values.namespace | default "adguard" }}
spec:
  volumeName: pv-data-adguard-home
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistence.size | default "1Gi" }}
  storageClassName: local-path
---
# AdGuard Home Application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: adguard-home-app
spec:
  project: {{ .Values.argocd.project | default "default" }}
  destination:
    name: {{ .Values.argocd.destinationName | default "in-cluster" }}
    namespace: {{ .Values.namespace | default "adguard" }}
  source:
    repoURL: {{ .Values.argocd.repoURL | default "https://k8s-at-home.com/charts/" }}
    chart: adguard-home
    targetRevision: {{ .Values.argocd.targetRevision | default "5.5.2" }}
    helm:
      valuesObject:
        controller:
          replicas: {{ .Values.controller.replicas | default "1" }}
        image:
          repository: {{ .Values.image.repository | default "adguard/adguardhome" }}
          tag: {{ .Values.image.tag | default "latest" }}
          pullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
        
        env:
          TZ: {{ .Values.timezone | default "UTC" }}
        
    
        ingress:
          main:
            enabled: {{ .Values.ingress.enabled | default false }}
            annotations:
              kubernetes.io/ingress.class: {{ .Values.ingress.class | default "traefik" }}
            hosts:
              - host: {{ .Values.ingress.host | default "adguard.local" }}
                paths:
                  - path: /
                    pathType: Prefix
            {{- if .Values.ingress.tls }}
            tls:
              - secretName: {{ .Values.ingress.tlsSecretName | default "adguard-tls" }}
                hosts:
                  - {{ .Values.ingress.host | default "adguard.local" }}
            {{- end }}
            
        persistence:
          config:
            enabled: true
            existingClaim: data-adguard-home

        {{- if .Values.service }}
        service:
          {{- toYaml .Values.service | nindent 10 }}
        {{- end }}
            
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory | default "128Mi" }}
            cpu: {{ .Values.resources.requests.cpu | default "100m" }}
          limits:
            memory: {{ .Values.resources.limits.memory | default "512Mi" }}
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{ end }}
