apiVersion: v1
kind: Service
metadata:
  name: {{ include "adguard.fullname" . }}
  labels:
    {{- include "adguard.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.webPort | default 80 }}
      targetPort: admin
      protocol: TCP
      name: admin
    - port: {{ .Values.service.httpsPort | default 443 }}
      targetPort: https
      protocol: TCP
      name: https
    - port: 53
      targetPort: dns-tcp
      protocol: TCP
      name: dns-tcp
    - port: 53
      targetPort: dns-udp
      protocol: UDP
      name: dns-udp
  selector:
    {{- include "adguard.selectorLabels" . | nindent 4 }} 