# Default values for AdGuard Home
replicaCount: 1

image:
  repository: adguard/adguardhome
  tag: ""
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}

service:
  type: ClusterIP
  webPort: 80
  httpsPort: 443

ingress:
  enabled: true
  className: "traefik"
  annotations:
    kubernetes.io/ingress.class: traefik
  hosts:
    - host: adguard.dmascotte.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: cert-manager-dmascotte-certificate
      hosts:
        - adguard.dmascotte.com

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 1Gi
  configSize: 100Mi
  # storageClass: "-"

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

# Default configuration values based on infrastructure.yaml
config:
  adguard:
    host: adguard.dmascotte.com
    username: admin
    password: admin
  dns:
    bind_hosts:
      - 0.0.0.0
    bootstrap_dns:
      - 1.1.1.1
      - 8.8.8.8
    protection_enabled: true
    blocking_mode: default
    filters_update_interval: 24
  web:
    bind_host: 0.0.0.0
    port: 80
