enabled: false

# Namespace for the AdGuard Home deployment
namespace: adguard

# ArgoCD configuration
argocd:
  project: default
  destinationName: in-cluster
  repoURL: https://k8s-at-home.com/charts/
  targetRevision: 5.5.2

# Image configuration
image:
  repository: adguard/adguardhome
  tag: latest
  pullPolicy: IfNotPresent

# Timezone configuration
timezone: UTC

# Persistence configuration
persistence:
  size: 1Gi
  nodeAffinity: raspberrypi

# Ingress configuration
ingress:
  enabled: true
  class: traefik
  host: adguard.dmascotte.com
  tls: true
  tlsSecretName: cert-manager-dmascotte-certificate

# Resource constraints
resources:
  requests:
    memory: 128Mi
    cpu: 100m
  limits:
    memory: 512Mi

# Network configuration
service:
  main:
    type: LoadBalancer
    loadBalancerIP: 192.168.1.2
#     ports:
#       http:
#         port: 80
#       dns-tcp:
#         enabled: true
#         port: 53
#         protocol: TCP
#       dns-udp:
#         enabled: true
#         port: 53
#         protocol: UDP