name: infrastructure

vault:
  enabled: true
  
postgres:
  enabled: false

redis:
  enabled: false

nextcloud:
  enabled: false

adguard:
  enabled: true
  service:
    main:
      enabled: false
  ingress:
    enabled: true
