name: infrastructure

vault:
  enabled: true
  
postgres:
  enabled: true

redis:
  enabled: true

nextcloud:
  enabled: true

adguard:
  enabled: true
  controller:
    replicas: 1
  resources:
    requests:
      memory: 680Mi
      cpu: 200m
    limits:
      memory: 1Gi
  service:
   main:
    type: LoadBalancer
    loadBalancerIP: 192.168.1.2
    externalTrafficPolicy: Cluster # Local
    # internalTrafficPolicy: Local # Cluster
    annotations:
      metallb.universe.tf/address-pool: metallb-ip-pool
      main:
    primary: true
    ports:
      http:
        enabled: true
        port: 3000
        protocol: TCP
        targetPort: 3000
      dns-tcp:
        enabled: true
        port: 53
        protocol: TCP
        targetPort: 53
      dns-udp:
        enabled: true
        port: 53
        protocol: UDP
        targetPort: 53
   dns-tcp:
    enabled: false
   dns-udp:
    enabled: false
  ingress:
    enabled: true
