name: infrastructure

vault:
  enabled: true
  
postgres:
  enabled: true

redis:
  enabled: true

nextcloud:
  enabled: true

adguard:
  enabled: true
  controller:
    replicas: 1
  resources:
    requests:
      memory: 680Mi
      cpu: 200m
    limits:
      memory: 1Gi
  service:
   main:
    type: LoadBalancer
    loadBalancerIP: 192.168.1.2
    externalTrafficPolicy: Cluster # Local
    # internalTrafficPolicy: Local # Cluster
    annotations:
      metallb.universe.tf/address-pool: metallb-ip-pool
      metallb.universe.tf/allow-shared-ip: "metallb-ip-pool"
    primary: true
    ports:
      http:
        enabled: true
        port: 3000
        protocol: TCP
        targetPort: 3000
      dns-tcp:
        enabled: true
        port: 53
        protocol: TCP
        targetPort: 53
      dns-udp:
        enabled: true
        port: 53
        protocol: UDP
        targetPort: 53
   dns-tcp:
    enabled: false
   dns-udp:
    enabled: false
  ingress:
    enabled: true

wireguard:
  enabled: false
  # controller:
  #   replicas: 1
  # resources:
  #   requests:
  #     memory: 256Mi
  #     cpu: 100m
  #   limits:
  #     memory: 512Mi
  # env:
  #   PUID: 1000
  #   PGID: 1000
  #   SERVERURL: auto
  #   PEERDNS: auto
  #   INTERNAL_SUBNET: 10.13.13.0/24
  #   ALLOWEDIPS: 0.0.0.0/0
  # service:
  #  main:
  #   type: LoadBalancer
  #   loadBalancerIP: 192.168.1.2
  #   externalTrafficPolicy: Local
  #   annotations:
  #     metallb.universe.tf/address-pool: metallb-ip-pool
  #     metallb.universe.tf/allow-shared-ip: "metallb-ip-pool"
  #   ports:
  #     wireguard:
  #       enabled: true
  #       port: 51820
  #       protocol: UDP
  #       targetPort: 51820
