name: infrastructure

postgres:
  enabled: true

vault:
  enabled: true 

redis:
  enabled: true

nextcloud:
  enabled: true

adguard:
  enabled: true
  # config for raspberry pi (192.168.1.2)
  service:
    type: ClusterIP
    webPort: 80
    httpsPort: 443
    
  ingress:
    enabled: true
    className: "traefik"
    annotations:
      kubernetes.io/ingress.class: traefik
    hosts:
      - host: adguard.dmascotte.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: cert-manager-dmascotte-certificate
        hosts:
          - adguard.dmascotte.com
  
  persistence:
    enabled: true
    storageClass: local-path
    accessMode: ReadWriteOnce
    size: 1Gi
    configSize: 100Mi
  
  # Ensure AdGuard runs on the Raspberry Pi
  nodeSelector:
    kubernetes.io/hostname: raspberrypi

  config:
    adguard:
      host: adguard.dmascotte.com
      username: admin
      password: admin
    dns:
      bind_hosts:
        - 0.0.0.0
      bootstrap_dns:
        - 1.1.1.1
        - 8.8.8.8
      protection_enabled: true
      blocking_mode: default
      filters_update_interval: 24
    web:
      bind_host: 0.0.0.0
      port: 80
