name: Release Helm Chart

on:
  push:
    paths:
      - 'charts/database/postgres/**'
    branches:
      - main

jobs:
  release-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.3

      - name: Package Helm chart
        run: |
          mkdir -p .output
          helm package charts/database/postgres --destination .output

      - name: Clone gh-pages branch
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git clone --branch gh-pages https://github.com/${{ github.repository }} gh-pages
          cp .output/*.tgz gh-pages/

      - name: Update index.yaml
        run: |
          cd gh-pages
          helm repo index . --url https://${{ github.repository_owner }}.github.io/$(basename ${{ github.repository }})
          git add .
          git commit -m "Update chart index for postgres" || echo "No changes to commit"
          git push
